bindkey -v 
# map jk to escape
bindkey -M viins 'jk' vi-cmd-mode
bindkey "^R" history-incremental-search-backward

export DEFAULT_USER="$(whoami)"

if [ -d "$HOME/miniconda3" ]; then
	CONDA_NAME="miniconda3"
else
	CONDA_NAME="anaconda3"
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/$CONDA_NAME/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/$CONDA_NAME/etc/profile.d/conda.sh" ]; then
        . "$HOME/$CONDA_NAME/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/$CONDA_NAME/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


if [ -f ~/load_cluster_modules.sh ]; then
    source "$HOME/load_cluster_modules.sh"
fi

alias vim='nvim'
alias ll="ls -l"
alias llt="ls -lt"

# get ls to colorize its outputs
export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

# use block in normal mode and beam in insert mode
# link: https://thevaluable.dev/zsh-install-configure-mouseless/
cursor_mode() {
    # See https://ttssh2.osdn.jp/manual/4/en/usage/tips/vim.html for cursor shapes
    cursor_block='\e[2 q'
    cursor_beam='\e[6 q'

    function zle-keymap-select {
        if [[ ${KEYMAP} == vicmd ]] ||
            [[ $1 = 'block' ]]; then
            echo -ne $cursor_block
        elif [[ ${KEYMAP} == main ]] ||
            [[ ${KEYMAP} == viins ]] ||
            [[ ${KEYMAP} = '' ]] ||
            [[ $1 = 'beam' ]]; then
            echo -ne $cursor_beam
        fi
    }

    zle-line-init() {
        echo -ne $cursor_beam
    }

    zle -N zle-keymap-select
    zle -N zle-line-init
}

cursor_mode

# function to get the conda environment name
# https://unix.stackexchange.com/a/701293
function parse_conda_env () {
    if [ ! -z "$CONDA_DEFAULT_ENV" ] # non-empty string
    then
		echo "($(basename "$CONDA_DEFAULT_ENV")) "
    fi
}

# Allows for functions in prompt
setopt PROMPT_SUBST 

# single quote to allow for re-evaluation
# https://www.makeuseof.com/customize-zsh-prompt-macos-terminal/
# link: https://unix.stackexchange.com/a/273567
PROMPT='%F{cyan}$(parse_conda_env)%F{yellow}%m %(6~|%-1~/.../%3~|%4~)> %f'
